[tool.poetry]
name = "pdf2img"
version = "0.1.0"
description = ""
authors = ["kinoshitakenta"]
readme = ""

[tool.poetry.dependencies]
python = "^3.9"
pdf2image = "^1.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
